## 06. pandas(3)

### 파일 입출력

In [1]:
import pandas as pd

In [ ]:
# csv 파일 불러오기
df = pd.read_csv("./dataset/practice_book_dataset.csv")
df.head()

In [4]:
# 데이터 정보 확인
df.shape
df.dtypes
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830 entries, 0 to 829
Data columns (total 19 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   title                         830 non-null    object
 1   author                        657 non-null    object
 2   price                         722 non-null    float64
 3   price (including used books)  722 non-null    object
 4   pages                         745 non-null    object
 5   avg_reviews                   702 non-null    float64
 6   n_reviews                     702 non-null    object
 7   star5                         702 non-null    object
 8   star4                         635 non-null    object
 9   star3                         554 non-null    object
 10  star2                         451 non-null    object
 11  star1                         328 non-null    object
 12  dimensions                    644 non-null    object
 13  weight                        651 non-null    object
 14  language                      759 non-null    object
 15  publisher                     714 non-null    object
 16  ISBN_13                       665 non-null    object
 17  link                          830 non-null    object
 18  complete_link                 830 non-null    object
dtypes: float64(2), object(17)
memory usage: 123.3+ KB

             price  avg_reviews
count   722.000000   702.000000
mean     46.491537     4.472080
std      63.292394     0.409608
min       0.990000     1.000000
25%      23.725000     4.325000
50%      39.490000     4.500000
75%      51.990000     4.700000
max    1318.740000     5.000000

In [5]:
df["title"].head(10)
df[["title","author"]].head(10)

,title,author
0,Data Analysis Using R (Low Priced Edition): A ...,[ Dr Dhaval Maheta]
1,Head First Data Analysis: A learner's guide to...,NaN
2,Guerrilla Data Analysis Using Microsoft Excel:...,"[ Oz du Soleil, and , Bill Jelen]"
3,Python for Data Analysis: Data Wrangling with ...,[ William McKinney]
4,Excel Data Analysis For Dummies (For Dummies (...,[ Paul McFedries]
5,Everything Data Analytics: A Beginner's Guide ...,NaN
6,SQL for Data Analysis: Advanced Techniques for...,[ Cathy Tanimura]
7,Qualitative Data Analysis: A Methods Sourcebook,"[ Matthew B. Miles, A. Michael Huberman, et al.]"
8,Topological Data Analysis with Applications,"[ Gunnar Carlsson, and , Mikael Vejdemo-Johan..."
9,"R in Action, Third Edition: Data analysis and ...",[ Robert I. Kabacoff]

In [ ]:
df2 = df.copy()
df2["libarary"] = "seoul library"
df2.to_csv("new_book_dataset.csv")

In [ ]:
mask = df["price"] >= 100
df[mask]
df.loc[mask, ["title", "price", "avg_reviews"]]

In [ ]:
df.isnull().sum()

In [8]:
# excel 파일 불러오기
df = pd.read_excel("./dataset/practice_employee_dataset.xlsx")
df.head()

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date
0,E02387,Emily Davis,Sr. Manger,IT,Research & Development,Female,Black,55,2016-04-08,141604,0.15,United States,Seattle,2021-10-16
1,E04105,Theodore Dinh,Technical Architect,IT,Manufacturing,Male,Asian,59,1997-11-29,99975,0.00,China,Chongqing,NaT
2,E02572,Luna Sanders,Director,Finance,Speciality Products,Female,Caucasian,50,2006-10-26,163099,0.20,United States,Chicago,NaT
3,E02832,Penelope Jordan,Computer Systems Manager,IT,Manufacturing,Female,Caucasian,26,2019-09-27,84913,0.07,United States,Chicago,NaT
4,E01639,Austin Vo,Sr. Analyst,Finance,Manufacturing,Male,Asian,55,1995-11-20,95409,0.00,United States,Phoenix,NaT

In [9]:
# excel(xlsx) 파일로 저장
df2 = df.copy()
df2["Working Period"] = 3
df2.head(10)
df.to_excel("./dataset/New_employee_dataset.xlsx")

In [10]:
df = pd.read_csv("./dataset/dataset.csv")
df.describe()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3065 entries, 0 to 3064
Data columns (total 17 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Year                                3065 non-null   int64
 1   Month                               3065 non-null   int64
 2   Sector                              3065 non-null   object
 3   Hydroelectric Power                 3065 non-null   float64
 4   Geothermal Energy                   3065 non-null   float64
 5   Solar Energy                        3065 non-null   float64
 6   Wind Energy                         3065 non-null   float64
 7   Wood Energy                         3065 non-null   float64
 8   Waste Energy                        3065 non-null   float64
 9   Fuel Ethanol, Excluding Denaturant  3065 non-null   float64
 10  Biomass Losses and Co-products      3065 non-null   float64
 11  Biomass Energy                      3065 non-null   float64
 12  Total Renewable Energy              3065 non-null   float64
 13  Renewable Diesel Fuel               3065 non-null   float64
 14  Other Biofuels                      3065 non-null   float64
 15  Conventional Hydroelectric Power    3065 non-null   float64
 16  Biodiesel                           3065 non-null   float64
dtypes: float64(14), int64(2), object(1)
memory usage: 407.2+ KB

In [5]:
df = pd.read_excel("dataset/dataset2.xlsx")
df

c:\Users\user\anaconda3\envs\data_analysis\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,에너지원별(1),에너지원별(2),에너지원별(3),에너지원별(4),2020,2021,2022,2023
0,총발전량 (MWh),소계,소계,소계,579999196,611015325,626448138,624883407
1,NaN,양수발전,소계,소계,3271019,3682932,3715049,3783877
2,신재생에너지 공급비중 (%),소계,소계,소계,7.44,8.29,9.22,9.67
3,NaN,재생에너지,소계,소계,6.41,7.15,8.05,8.5
4,NaN,신에너지,소계,소계,1.02,1.14,1.18,1.16
...,...,...,...,...,...,...,...,...
76,② 신에너지,연료전지 (MWh),소계,소계,3544354,4798120,5409625,6257348
77,NaN,NaN,사업용,소계,3485608,4727370,5329684,6164458
78,NaN,NaN,자가용,소계,58746,70750,79942,92889
79,NaN,IGCC (MWh),소계,소계,2377374,2190755,1964827,996517
80,NaN,NaN,사업용,소계,2377374,2190755,1964827,996517